config/routes.rb
Rails.application.routes.draw do
  root :to => 'sections#index'

  resources :sections do
    resources :weeks, :except => [:index]
  end
end

app/models/section.rb
class Section < ActiveRecord::Base
  has_many :weeks
  
  validates :name, :presence => true
end

app/models/week.rb
class Week < ActiveRecord::Base
  belongs_to :section

  validates :name, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  def index
    @sections = Section.all
  end

  def show
    @section = Section.find(params[:id])
  end

  def new
    @section = Section.new
  end

  def create
    @section = Section.new(section_params)
    if @section.save
      flash[:notice] = "Section successfully added!"
      redirect_to sections_path
    else
      render :new
    end
  end

  def edit
    @section = Section.find(params[:id])
  end

  def update
    @section = Section.find(params[:id])
    if @section.update(section_params)
      flash[:notice] = "Section successfully updated!"
      redirect_to sections_path
    else
      render :edit
    end
  end

  def destroy
    @section = Section.find(params[:id])
    @section.destroy
    flash[:notice] = "Section deleted."
    redirect_to sections_path
  end

private
  def section_params
    params.require(:section).permit(:name)
  end
end

app/controllers/weeks_controller.rb
class WeeksController < ApplicationController
  def show
    @section = Section.find(params[:section_id])
    @week = @section.weeks.find(params[:id])
  end

  def new
    @section = Section.find(params[:section_id])
    @week = @section.weeks.new
  end

  def create
    @section = Section.find(params[:section_id])
    @week = @section.weeks.new(week_params)
    if @week.save
      flash[:notice] = "Week successfully added!"
      redirect_to sections_path(@week.section)
    else
      render :new
    end
  end

  def edit
    @week = Week.find(params[:id])
  end

  def update
    @week = Week.find(params[:id])
    if @week.update(week_params)
      flash[:notice] = "Week successfully updated!"
      redirect_to sections_path
    else
      render :edit
    end
  end

  def destroy
    @week = Week.find(params[:id])
    @week.destroy
    flash[:notice] = "Week deleted."
    redirect_to sections_path(@week.section)
  end

private
  def week_params
    params.require(:week).permit(:name, :section_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= flash[:alert] %>
<%= flash[:notice] %>

<%= yield %>

<li><a href="/">Home</a></li>

</body>
</html>

app/views/sections/_form.html.erb
<%= render "layouts/errors", :object => @section %>

<%= form_for @section do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/sections/edit.html.erb
<h1>Edit Section Name</h1>

<%= render 'form' %>

app/views/sections/index.html.erb
<h1>Sections</h1>

<ul>
  <% @sections.each do |section| %>
    <li><%= link_to section.name, section_path(section) %></li>
  <% end %>
</ul>

  <p><a href="/sections/new">Create a new Section</a></p>

app/views/sections/new.html.erb
<h1>New Section</h1>

<%= render 'form' %>

app/views/sections/show.html.erb
<% content_for(:title, "Section | Learn How To Program") %>

<h1><%= @section.name %></h1>

<% if @section.weeks.any? %>
<h4>Here are the weeks for this section:</h4>

  <ul>
    <% @section.weeks.each do |week| %>

    <li>
      <%= link_to week.name, section_week_path(@section, week) %>
      <%= link_to "Edit", edit_section_week_path(@section, week) %> |
      <%= link_to "Delete", section_week_path(@section, week),
                            :data => {:confirm =>"Woooord?",
                                      :method => "delete"} %>
    </li>
    <% end %>
  </ul>
  <% else %>
    <p>
      There are no weeks!
    </p>
  <% end %>

<p>
  <%= link_to "Add Week", new_section_week_path(@section) %>
</p>

<p>
  <%= link_to "Edit Section", edit_section_path(@section) %>
</p>

<p>
  <%= link_to "Delete Section", section_path(@section),
                          :data => {:confrim => "For Reals?",
                                    :method => "delete"} %>
</p>

app/views/weeks/_form.html.erb
<%= render('layouts/errors', :object => @week) %>

<%= form_for [@section, @week] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/weeks/new.html.erb
<% content_for(:title, "New Week | Learn How To Program") %>

<h1>New Week for <%= @section.name %></h1>

<%= render 'form' %>

app/views/weeks/show.html.erb
<% content_for(:title, "Section | Learn How To Program") %>

<h1><%= @week.name %></h1>

<% if @section.weeks.any? %>
<h4>Here are the weeks for this section:</h4>

<ul>
  <% @section.weeks.each do |week| %>

  <li>
    <%= link_to week.name, section_week_path(@section, week) %>
    <%= link_to "Edit", edit_section_week_path(@section, week) %> |
    <%= link_to "Delete", section_week_path(@section, week),
    :data => {:confirm =>"Woooord?",
      :method => "delete"} %>
    </li>
    <% end %>
  </ul>
  <% else %>
  <p>
    There are no weeks!
  </p>
  <% end %>

  <p>
    <%= link_to "Add Week", new_section_week_path(@section) %>
  </p>

  <p>
    <%= link_to "Edit Section", edit_section_path(@section) %>
  </p>

  <p>
    <%= link_to "Delete Section", section_path(@section),
    :data => {:confrim => "For Reals?",
      :method => "delete"} %>
    </p>
    